name: smollm2
base: core24
summary: SmolLM2 inference snap
description: |
  SmolLM2 is a compact large language model (LLM) developed by Hugging Face.
  It is designed for efficient natural language tasks such as text generation,
  summarization, and question answering.

  This snap lets you run SmolLM2 locally.

  Before you start, make sure to have the necessary drivers installed on the host:
  https://documentation.ubuntu.com/inference-snaps/how-to/install-drivers/

  **Install:**
  
  `sudo snap install smollm2`
  
  **Get help:**
  
  `smollm2 --help`
  
  **Licensing:**
  
  The SmolLM2 model is provided by Hugging Face under the Apache 2.0 license.

  The licenses of all bundled software can be found inside the snap at `/snap/smollm2/current/usr/share/doc`.

website: https://documentation.ubuntu.com/inference-snaps
source-code: https://github.com/canonical/smollm2-snap
issues: https://github.com/canonical/inference-snaps/issues

adopt-info: version

grade: stable
confinement: strict
compression: lzo

assumes:
  - snapd2.68 # for components support

platforms:
  amd64:
  arm64:

# plugs:
  # To allow side-loading models into server (root daemon) from user home directory
  # home:
  #   read: all

environment:
  SNAP_COMPONENTS: /snap/$SNAP_INSTANCE_NAME/components/$SNAP_REVISION
  ARCH_TRIPLET: $CRAFT_ARCH_TRIPLET_BUILD_FOR

layout:
  # Under wsl the libraries are expected in /usr/lib/wsl
  /usr/lib/wsl:
    bind: $SNAP_COMMON/usr/lib/wsl

hooks:
  install:
    plugs: &install-plugs
      # For hardware detection
      - hardware-observe
      - opengl
  post-refresh:
    plugs: *install-plugs

parts:
  version:
    after: [cli]
    plugin: nil
    source: . # To regenerate the git hash on every change
    build-packages:
      - jq
      - git
    override-pull: |
      # Do nothing. This significantly reduces build time when sourcing large files.
    override-build: |
      set -eo pipefail
      cli_version=$($CRAFT_STAGE/bin/modelctl version --format=json | jq .cli --raw-output)
      git_hash=$(git -C "$SNAPCRAFT_PROJECT_DIR" describe --always)
      craftctl set version="${cli_version#v}+${git_hash}"

  cli:
    source:
      - on amd64: https://github.com/canonical/inference-snaps-cli/releases/download/v2.0.0-beta.11/inference-snaps-cli-linux-amd64.tar.xz
      - on arm64: https://github.com/canonical/inference-snaps-cli/releases/download/v2.0.0-beta.11/inference-snaps-cli-linux-arm64.tar.xz
    plugin: dump
    override-build: |
      # For tab completion
      ln --symbolic ./modelctl bin/smollm2

      craftctl default
    
  cli-lspci:
    plugin: nil
    stage-packages:
      - pciutils # lspci

  # Used for NVIDIA vRAM and CUDA Capability detection.
  # Only the binary is included to avoid staging libraries, which should instead be provided by the host through the opengl interface.
  cli-nvidia-smi:
    plugin: nil
    build-packages:
      - nvidia-utils-580
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp /usr/bin/nvidia-smi $CRAFT_PART_INSTALL/usr/bin/
      
      license_dir=$CRAFT_PART_INSTALL/usr/share/doc/nvidia-utils-580/
      mkdir -p $license_dir
      cp /usr/share/doc/nvidia-utils-580/copyright $license_dir/

  webui:
    plugin: dump
    source: https://github.com/canonical/inference-snaps-webui/releases/download/v1.1.0/inference-snaps-webui.tar.xz
    organize:
      "*": webui/

  engines:
    source: engines
    plugin: dump
    organize:
      "*": engines/

  models:
    source: models
    plugin: dump
    organize:
      "*": models/

  runtimes:
    source: runtimes
    plugin: dump
    organize:
      "*": runtimes/
  
  scripts:
    source: scripts
    plugin: dump
    stage-packages:
      - jq
    organize:
      "server.sh": bin/
      "server-webui.sh": bin/
      "export-shared-configs.sh": bin/

  local-component-files:
    plugin: cmake # an out-of-source plugin to reduce copies on disk
    source: components
    override-build:
      cp -rf --archive --link --no-dereference ${CRAFT_PART_SRC}/* ${CRAFT_PART_INSTALL}
    organize:
      "llamacpp/*": (component/llamacpp)
      "llamacpp-cuda/*": (component/llamacpp-cuda)
      "smollm2-135m-q4-k-m-gguf/*": (component/smollm2-135m-q4-k-m-gguf)
      
    prime:
      # Exclude everything not explicitly organized
      - -*

  llamacpp:
    plugin: dump
    source: 
      - on amd64: https://github.com/canonical/llama.cpp-builds/releases/download/b9482/llamacpp-amd64.tar.gz
      - on arm64: https://github.com/canonical/llama.cpp-builds/releases/download/b9482/llamacpp-arm64.tar.gz
    stage-packages:
      - libgomp1
    organize:
      "licenses": usr/share/doc/llama.cpp # Add licenses to the snap
      "*": (component/llamacpp)
    
  llamacpp-cuda:
    plugin: dump
    source: 
      - on amd64: https://github.com/canonical/llama.cpp-builds/releases/download/b9482/llamacpp-amd64+cuda12.9.tar.gz
      - on arm64: https://github.com/canonical/llama.cpp-builds/releases/download/b9482/llamacpp-arm64+cuda12.9.tar.gz
    stage-packages:
      - libgomp1
    organize:
      "licenses": usr/share/doc/llama.cpp+cuda # Add licenses to the snap
      "*": (component/llamacpp-cuda)

  notice:
    plugin: nil
    source: NOTICE
    source-type: file
    override-build: |
      license_dir=$CRAFT_PART_INSTALL/usr/share/doc
      mkdir -p $license_dir
      cp NOTICE $license_dir/
      cp $SNAPCRAFT_PROJECT_DIR/LICENSE $license_dir/
      cp $SNAPCRAFT_PROJECT_DIR/LICENSE-smollm2 $license_dir/

components:
  smollm2-135m-q4-k-m-gguf:
    type: standard
    summary: SmolLM2 135M Instruct Q4_K_M GGUF
    description: Model weights for SmolLM2 135M Instruct in GGUF format

  llamacpp:
    type: standard
    summary: llama.cpp using default CPU instruction sets
    description: LLM inference in C/C++
  
  llamacpp-cuda:
    type: standard
    summary: llama.cpp with CUDA backend
    description: LLM inference in C/C++

apps:
  smollm2:
    command: bin/modelctl
    completer: bin/snap-completer.bash
    plugs:
      - hardware-observe
      - opengl
      - network
      - desktop # To open the webui in the browser
    environment:
      ADDITIONAL_FEATURES: chat, webui

  server:
    command: bin/server.sh
    daemon: simple
    plugs:
      - network-bind
      - hardware-observe
      - opengl
      - home

  server-webui:
    command: bin/server-webui.sh
    daemon: simple
    plugs:
      - network-bind
